version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db 

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      TEST_DB_URL: 'mongodb://mongodb:27017/test'
      DEV_DB_URL: 'mongodb://mongodb:27017/nest'
      PROD_DB_URL: 'mongodb://mongodb:27017/nest'
      APP_URL: 'http://localhost:3000'
      SECRET_KEY: 'SECRET'
      AWS_ACCESS_KEY_ID: 'xxx'
      AWS_SECRET_ACCESS_KEY: 'xxx'
      AWS_BUCKET_NAME: mihalishcher.avatar
      AWS_REGION: eu-central-1   
    depends_on:
      - mongodb

volumes:
 mongodb: {} 